# Blood Bank Master Dataset — Table Generation & Synthetic Data Pipeline

**Source file:** `blood_bank_master_clean.csv`  
**Records:** 2,817 rows × 28 columns  
**Scope:** 35 States/UTs across India  
**Purpose:** Normalise into relational tables; generate synthetic donor & donation data  
**Date:** June 2026

---

## Tables generated in this notebook

| # | Table | Description | Rows (approx.) |
|---|-------|-------------|----------------|
| 1 | `state` | One row per unique State/UT | ~35 |
| 2 | `district` | One row per unique District × State | ~600 |
| 3 | `city` | One row per unique City × District × State | ~900 |
| 4 | `category` | Blood bank categories (Govt / Pvt / Charity…) | ~5 |
| 5 | `blood_bank` | Core fact table — one row per blood bank | ~2,817 |
| 6 | `donor` | Synthetic donor profiles | 50,000 |
| 7 | `donation_event` | Synthetic individual donation records | ~35,000 |
| 8 | `blood_inventory` | Aggregated units per bank × blood group | ~15,000 |

---

## 0. Imports & Setup

In [3]:
import pandas as pd
import numpy as np
import re
from datetime import datetime, timedelta

pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', 80)

INPUT_FILE = 'blood_bank_master_clean.csv'

print('Libraries loaded successfully.')

Libraries loaded successfully.

---
## 1. Load Clean Data

Reading from the cleaned CSV produced by `blood_bank_data_cleaning.ipynb`.  
All fixes (city normalisation, casing, dates, phone numbers, etc.) are already applied.

In [4]:
df_master = pd.read_csv(INPUT_FILE, dtype=str, low_memory=False)

# Strip any residual whitespace from column names and cell values
df_master.columns = df_master.columns.str.strip()
df_master = df_master.apply(
    lambda col: col.str.strip() if col.dtype == object else col
)

print(f'Loaded : {df_master.shape[0]} rows x {df_master.shape[1]} columns')
print(f'Columns: {df_master.columns.tolist()}')

Loaded : 2817 rows x 28 columns
Columns: ['Sr No', 'Blood Bank Name', 'State', 'District', 'City', 'Address', 'Pincode', 'Contact No', 'Mobile', 'Helpline', 'Fax', 'Email', 'Website', 'Nodal Officer', 'Contact Nodal Officer', 'Mobile Nodal Officer', 'Email Nodal Officer', 'Qualification Nodal Officer', 'Category', 'Blood Component Available', 'Apheresis', 'Service Time', 'License #', 'Date License Obtained', 'Date of Renewal', 'Renewal Status', 'Latitude', 'Longitude']

---
## 2. Dimension Tables

Four lightweight lookup tables are built first — State, District, City, and Category.  
Each gets a surrogate integer primary key (`state_id`, `district_id`, etc.) that will  
be used as a foreign key in the main `blood_bank` fact table.

> **Join order matters:** State → District → City, each level referencing the one above.

### 2a. State Table

One row per unique State / UT name found in the dataset.  
Sorted alphabetically; `state_id` is a simple 1-based integer.

In [5]:
state_df = (
    df_master[['State']]
    .drop_duplicates()
    .sort_values('State')
    .reset_index(drop=True)
)

state_df['state_id'] = range(1, len(state_df) + 1)
state_df = state_df[['state_id', 'State']]

print(f'State table : {state_df.shape[0]} rows x {state_df.shape[1]} columns')
display(state_df.head(5))

State table : 36 rows x 2 columns

   state_id                        State
0         1  Andaman And Nicobar Islands
1         2               Andhra Pradesh
2         3            Arunachal Pradesh
3         4                        Assam
4         5                        Bihar

### 2b. District Table

One row per unique (District, State) pair — because the same district name can appear  
in multiple states (e.g. "Hamirpur" exists in both Uttar Pradesh and Himachal Pradesh).  
Each row carries the parent `state_id` as a foreign key.

In [6]:
district_df = (
    df_master[['District', 'State']]
    .drop_duplicates()
    .merge(state_df, on='State')
    .sort_values(['state_id', 'District'])
    .reset_index(drop=True)
)

district_df['district_id'] = range(1, len(district_df) + 1)
district_df = district_df[['district_id', 'District', 'state_id']]

print(f'District table : {district_df.shape[0]} rows x {district_df.shape[1]} columns')
display(district_df.head(5))

District table : 605 rows x 3 columns

   district_id       District  state_id
0            1  South Andaman         1
1            2      Anantapur         2
2            3       Chittoor         2
3            4  East Godavari         2
4            5         Guntur         2

### 2c. City Table

One row per unique (City, District, State) triplet.  
Using all three levels avoids false matches for city names shared across states  
(e.g. "Aurangabad" in Maharashtra, Bihar and Telangana must get distinct `city_id` values).  
Each row carries the parent `district_id` as a foreign key.

In [7]:
city_df = (
    df_master[['City', 'District', 'State']]
    .drop_duplicates()
    .merge(
        district_df.merge(state_df, on='state_id'),
        on=['District', 'State']
    )
    .sort_values(['district_id', 'City'])
    .reset_index(drop=True)
)

city_df['city_id'] = range(1, len(city_df) + 1)
city_df = city_df[['city_id', 'City', 'district_id']]

print(f'City table : {city_df.shape[0]} rows x {city_df.shape[1]} columns')
display(city_df.head(5))

City table : 1139 rows x 3 columns

   city_id          City  district_id
0        1    Port Blair            1
1        2     Anantapur            2
2        3  Bathalapalli            2
3        4      Guntakal            2
4        5      Hindupur            2

### 2d. Category Table

One row per unique blood bank category (e.g. `GOVT`, `PVT`, `CHARITY`).  
`category_id` is a simple 1-based integer.

In [8]:
category_df = (
    df_master[['Category']]
    .drop_duplicates()
    .sort_values('Category')
    .reset_index(drop=True)
)

category_df['category_id'] = range(1, len(category_df) + 1)
category_df = category_df[['category_id', 'Category']]

print(f'Category table : {category_df.shape[0]} rows x {category_df.shape[1]} columns')
display(category_df)

Category table : 4 rows x 2 columns

   category_id    Category
0            1     CHARITY
1            2  GOVERNMENT
2            3     PRIVATE
3            4         NaN

---
## 3. Blood Bank Fact Table

The main fact table: one row per blood bank.  

**Foreign key joins:**
- `city_id`  — resolved via **(City + District + State)** triplet to avoid cross-state name collisions  
- `category_id` — resolved via Category  

Raw geography columns (State, District, City) and the original `Sr No` are dropped  
after the IDs are assigned.  A new `blood_bank_id` (1-based) is the primary key.

**`bank_size`** is a derived attribute assigned here based on a plausible distribution  
(60 % small / 30 % medium / 10 % large) for use in downstream analytics.

In [9]:
# Build a lookup table: (City, District, State) → city_id
city_lookup = (
    city_df
    .merge(district_df[['district_id', 'District', 'state_id']], on='district_id')
    .merge(state_df[['state_id', 'State']], on='state_id')
    [['city_id', 'City', 'District', 'State']]
)

blood_bank_df = df_master.copy()

# Attach city_id using the full (City, District, State) key — avoids cross-state collisions
blood_bank_df = blood_bank_df.merge(
    city_lookup,
    on=['City', 'District', 'State'],
    how='left'
)

# Attach category_id
blood_bank_df = blood_bank_df.merge(
    category_df,
    on='Category',
    how='left'
)

# Assign surrogate primary key
blood_bank_df['blood_bank_id'] = range(1, len(blood_bank_df) + 1)

# Assign bank_size (synthetic, for downstream analytics)
np.random.seed(42)
blood_bank_df['bank_size'] = np.random.choice(
    ['small', 'medium', 'large'],
    size=len(blood_bank_df),
    p=[0.6, 0.3, 0.1]
)

# Select and order final columns — geography replaced by FK ids
blood_bank_df = blood_bank_df[[
    'blood_bank_id',
    'Blood Bank Name',
    'city_id',
    'category_id',

    'Address',
    'Pincode',

    'Contact No',
    'Mobile',
    'Helpline',
    'Fax',

    'Email',
    'Website',

    'Nodal Officer',
    'Contact Nodal Officer',
    'Mobile Nodal Officer',
    'Email Nodal Officer',
    'Qualification Nodal Officer',

    'Blood Component Available',
    'Apheresis',
    'Service Time',

    'License #',
    'Date License Obtained',
    'Date of Renewal',
    'Renewal Status',

    'Latitude',
    'Longitude',
    'bank_size',
]]

print(f'Blood Bank table : {blood_bank_df.shape[0]} rows x {blood_bank_df.shape[1]} columns')
print(f'city_id nulls    : {blood_bank_df["city_id"].isna().sum()} (should be 0)')
print(f'category_id nulls: {blood_bank_df["category_id"].isna().sum()} (should be 0)')
display(blood_bank_df.head(3))

Blood Bank table : 2817 rows x 27 columns
city_id nulls    : 0 (should be 0)
category_id nulls: 0 (should be 0)

,blood_bank_id,Blood Bank Name,city_id,category_id,Address,Pincode,Contact No,Mobile,Helpline,Fax,Email,Website,Nodal Officer,Contact Nodal Officer,Mobile Nodal Officer,Email Nodal Officer,Qualification Nodal Officer,Blood Component Available,Apheresis,Service Time,License #,Date License Obtained,Date of Renewal,Renewal Status,Latitude,Longitude,bank_size
0,1,G.B. Pant Hospital Blood Bank,1,2,Atlanta Point\r\nNear Cellular Jail\r\nP.O. Aberdeen Bazaar,744104,03192 230628,9434266561,102,NaN,bbgbpant@gmail.com,NaN,Dr.Ganesh Samaddar,03192 230628,9434266561,ganeshsamadder7@gmail.com,NaN,YES,NO,24x7,DL1/CLAA/ANI,14-06-1996,01-01-2012,NaN,11.675442,92.747338,small
1,2,I.N.H.S. Dhanvantri,1,2,"Ashvini Nagar, Port Blair, Andaman And Nicobar Islands.",744103,03192 248759,8001452200,NaN,NaN,NaN,NaN,Dr.Smiriti Mathur,03192 248759,8001452200,mesmriti@yahoo.com,"Mbbs, Md (Pathology)",NO,NO,24x7,DL2/CLAA/ANI,14-06-1996,31-12-2016,NaN,11.649693,92.717418,large
2,3,Pillar Health Centre Blood Bank,1,1,"Lamba Line,\r\nP.B. 526,\r\nP.O. Junglighat, \r\nOpposite Airport",744104,"03192 233193, 03192 233993",9474247585,03192 233193,NaN,pillarbloodbank2016@gmail.com,NaN,Dr. Sr. Cross Mary,"03192 233193, 03192 233993",9474247585,crossgracy2003@yahoo.co.in,"Mbbs, Md (Medicine)",NO,NO,24x7,DL3/CLAA/ANI,08-09-2010,10-06-2015,NaN,11.653229,92.730714,medium

---
## 4. Donor Table

50,000 synthetic donor profiles.  

**City assignment** is weighted by the number of blood banks in each city — cities with  
more banks are assumed to have proportionally larger donor populations.  

**Blood group distribution** follows published Indian population frequencies  
(O+ most common at ~37 %; AB- rarest at ~0.2 %).  Probabilities are normalised to  
sum to exactly 1.0 before being passed to NumPy.  

**Gender split**: 70 % Male / 30 % Female (reflects known donor demographics in India).  

**Age**: uniform draw between 18 and 59 (eligible donation age range).

In [10]:
np.random.seed(42)

N_DONORS = 50_000

# Weight cities by number of blood banks (proxy for donor population density)
city_weights = (
    blood_bank_df.groupby('city_id')
    .size()
    .reset_index(name='num_banks')
)
city_weights['weight'] = city_weights['num_banks'] / city_weights['num_banks'].sum()

# Blood group frequencies (Indian population)
BLOOD_GROUPS = ['O+', 'B+', 'A+', 'AB+', 'O-', 'A-', 'B-', 'AB-']
BLOOD_PROBS  = np.array([0.37, 0.32, 0.22, 0.07, 0.01, 0.005, 0.003, 0.002])
BLOOD_PROBS  = BLOOD_PROBS / BLOOD_PROBS.sum()   # normalise — guarantees exact sum to 1.0

donor_df = pd.DataFrame({
    'donor_id'   : range(1, N_DONORS + 1),
    'city_id'    : np.random.choice(city_weights['city_id'],
                                    size=N_DONORS, p=city_weights['weight']),
    'blood_group': np.random.choice(BLOOD_GROUPS, size=N_DONORS, p=BLOOD_PROBS),
    'gender'     : np.random.choice(['M', 'F'], size=N_DONORS, p=[0.7, 0.3]),
    'age'        : np.random.randint(18, 60, N_DONORS),
    'is_active'  : True,
})

print(f'Donor table : {donor_df.shape[0]} rows x {donor_df.shape[1]} columns')
print()
print('Blood group distribution:')
print((donor_df['blood_group'].value_counts(normalize=True) * 100).round(2).to_string())
display(donor_df.head(5))

Donor table : 50000 rows x 6 columns

Blood group distribution:
blood_group
O+     37.04
B+     31.83
A+     22.41
AB+     6.82
O-      0.98
A-      0.47
B-      0.24
AB-     0.21

   donor_id  city_id blood_group gender  age  is_active
0         1      458          A+      M   36       True
1         2     1070          B+      M   39       True
2         3      832          O+      M   19       True
3         4      680          A+      M   25       True
4         5      190          B+      M   53       True

---
## 5. Donation Events

Each donor may have donated 0–4 times over the past 2 years.  
Successive donations are spaced at least 90 days apart (the standard minimum gap).  
The donation is recorded at a blood bank in the donor's own city; if no bank exists  
in that city, any bank in the dataset is eligible.

Event timestamps are then randomised uniformly across the 2-year window and the  
table is sorted chronologically.  Final `event_id` is re-assigned after sorting.

In [11]:
np.random.seed(42)

today = pd.Timestamp.now()

# Pre-build city → blood_bank_id lookup for speed
city_bank_map = (
    blood_bank_df.groupby('city_id')['blood_bank_id']
    .apply(list)
    .to_dict()
)

all_bank_ids = blood_bank_df['blood_bank_id'].tolist()

events = []
event_id = 1

for _, donor in donor_df.iterrows():

    num_donations = np.random.choice([0, 1, 2, 3, 4], p=[0.30, 0.30, 0.20, 0.15, 0.05])
    if num_donations == 0:
        continue

    # Build donation date sequence starting at a random point in the past 2 years
    donation_dates = []
    current_date = today - pd.Timedelta(days=int(np.random.randint(0, 730)))

    for _ in range(num_donations):
        donation_dates.append(current_date)
        current_date += pd.Timedelta(days=int(np.random.randint(90, 180)))
        if current_date > today:
            break

    # Resolve blood banks for this donor's city
    city_banks = city_bank_map.get(donor['city_id'], all_bank_ids)

    for donation_date in donation_dates:
        events.append({
            'event_id'      : event_id,
            'donor_id'      : donor['donor_id'],
            'blood_bank_id' : np.random.choice(city_banks),
            'blood_group'   : donor['blood_group'],
            'units_donated' : 1,
            'event_time'    : donation_date,
        })
        event_id += 1

donation_event_df = pd.DataFrame(events)

# Randomise timestamps uniformly across the 2-year window, then sort chronologically
start_date = today - pd.Timedelta(days=730)
random_seconds = np.random.randint(
    0,
    int((today - start_date).total_seconds()),
    size=len(donation_event_df)
)
donation_event_df['event_time'] = start_date + pd.to_timedelta(random_seconds, unit='s')
donation_event_df = donation_event_df.sort_values('event_time').reset_index(drop=True)
donation_event_df['event_id'] = range(1, len(donation_event_df) + 1)

print(f'Donation Event table : {donation_event_df.shape[0]} rows x {donation_event_df.shape[1]} columns')
print(f'Unique timestamps    : {donation_event_df["event_time"].nunique()}')
display(donation_event_df.head(5))

Donation Event table : 58645 rows x 6 columns
Unique timestamps    : 58633

,event_id,donor_id,blood_bank_id,blood_group,units_donated,event_time
0,1,49414,1609,A+,1,2024-06-23 23:10:48.899398
1,2,15341,1989,B+,1,2024-06-23 23:16:16.899398
2,3,6265,2373,O+,1,2024-06-23 23:17:52.899398
3,4,20072,431,B+,1,2024-06-23 23:21:33.899398
4,5,49773,2223,O+,1,2024-06-23 23:28:22.899398

---
## 6. Blood Inventory Table

Aggregates total units donated per blood bank × blood group from the donation events.  
Each row represents the cumulative stock at a given bank for one blood group.  
`inventory_id` is a simple 1-based surrogate key.

In [12]:
inventory_df = (
    donation_event_df
    .groupby(['blood_bank_id', 'blood_group'])['units_donated']
    .sum()
    .reset_index()
    .rename(columns={'units_donated': 'units_available'})
    .sort_values(['blood_bank_id', 'blood_group'])
    .reset_index(drop=True)
)

inventory_df.insert(0, 'inventory_id', range(1, len(inventory_df) + 1))

print(f'Blood Inventory table : {inventory_df.shape[0]} rows x {inventory_df.shape[1]} columns')
display(inventory_df.head(10))

Blood Inventory table : 11159 rows x 4 columns

   inventory_id  blood_bank_id blood_group  units_available
0             1              1          A+                6
1             2              1         AB+                1
2             3              1          B+                3
3             4              1          O+                8
4             5              1          O-                1
5             6              2          A+                7
6             7              2         AB+                2
7             8              2          B+                3
8             9              2          O+               11
9            10              3          A+                5

---
## 7. Upload to Database

All eight tables are uploaded to a PostgreSQL instance (NeonDB).  
`if_exists='replace'` drops and recreates each table on every run — safe for  
development; switch to `'append'` or a proper migration strategy for production.

Tables are uploaded in dependency order so foreign key constraints (if applied later)  
are satisfied: State → District → City → Category → Blood Bank → Donor → Donation Event → Inventory.

In [13]:
import pandas as pd
import psycopg2
from sqlalchemy import create_engine

DATABASE_URL = "postgresql://neondb_owner:npg_3sINW4GupYoA@ep-polished-fog-aii4b63t.c-4.us-east-1.aws.neon.tech/neondb?sslmode=require"

# Test connection
conn = psycopg2.connect(
    host="ep-polished-fog-aii4b63t.c-4.us-east-1.aws.neon.tech",
    port=5432,
    database="neondb",
    user="neondb_owner",
    password="npg_3sINW4GupYoA",
    sslmode="require"
)

print("PostgreSQL connection successful!")
conn.close()

# SQLAlchemy engine
engine = create_engine(DATABASE_URL)

PostgreSQL connection successful!

In [25]:
import pandas as pd
import psycopg2
from sqlalchemy import create_engine
from dotenv import load_dotenv
import os

# Load variables from .env
load_dotenv()

DB_HOST = os.getenv("DB_HOST")
DB_PORT = os.getenv("DB_PORT")
DB_NAME = os.getenv("DB_NAME")
DB_USER = os.getenv("DB_USER")
DB_PASSWORD = os.getenv("DB_PASSWORD")
DB_SSLMODE = os.getenv("DB_SSLMODE")
DATABASE_URL = os.getenv("DATABASE_URL")

# Test PostgreSQL connection
conn = psycopg2.connect(
    host=DB_HOST,
    port=DB_PORT,
    database=DB_NAME,
    user=DB_USER,
    password=DB_PASSWORD,
    sslmode=DB_SSLMODE
)

print("PostgreSQL connection successful!")
conn.close()

# SQLAlchemy engine
if DATABASE_URL is None:
    raise ValueError("DATABASE_URL is not set in the environment")

engine = create_engine(DATABASE_URL)

print("SQLAlchemy engine created successfully!")

PostgreSQL connection successful!
SQLAlchemy engine created successfully!

In [15]:
# ── Upload all tables in dependency order ───────────────────────────────────


UPLOAD_PLAN = [
    ('state',           state_df),
    ('district',        district_df),
    ('city',            city_df),
    ('category',        category_df),
    ('blood_bank',      blood_bank_df),
    ('donor',           donor_df),
    ('donation_event',  donation_event_df),
    ('blood_inventory', inventory_df),
]

for table_name, df_to_upload in UPLOAD_PLAN:
    df_to_upload.to_sql(table_name, engine, if_exists='replace', index=False)
    print(f'  ✓  {table_name:<20}  {len(df_to_upload):>6} rows uploaded')

print()
print('All tables uploaded successfully.')

  ✓  state                     36 rows uploaded
  ✓  district                 605 rows uploaded
  ✓  city                    1139 rows uploaded
  ✓  category                   4 rows uploaded
  ✓  blood_bank              2817 rows uploaded
  ✓  donor                  50000 rows uploaded
  ✓  donation_event         58645 rows uploaded
  ✓  blood_inventory        11159 rows uploaded

All tables uploaded successfully.

---
## 8. Verification

Quick sanity checks against the live database — confirms that row counts match  
local DataFrames and that the uploaded data is queryable.

In [16]:
# ── Confirm tables exist in the database ────────────────────────────────────
tables_in_db = pd.read_sql(
    """
    SELECT table_name
    FROM   information_schema.tables
    WHERE  table_schema = 'public'
    ORDER  BY table_name
    """,
    engine
)

print('Tables in database:')
print(tables_in_db['table_name'].tolist())

Tables in database:
['blood_bank', 'blood_inventory', 'category', 'city', 'district', 'donation_event', 'donor', 'playing_with_neon', 'state']

In [17]:
# ── Row count validation ────────────────────────────────────────────────────
print(f'{"Table":<20}  {"Local rows":>10}  {"DB rows":>10}  {"Match":>6}')
print('-' * 52)

for table_name, df_local in UPLOAD_PLAN:
    db_count = pd.read_sql(f'SELECT COUNT(*) AS n FROM {table_name}', engine)['n'].iloc[0]
    local_count = len(df_local)
    match = '✓' if db_count == local_count else '✗ MISMATCH'
    print(f'{table_name:<20}  {local_count:>10}  {db_count:>10}  {match:>6}')

Table                 Local rows     DB rows   Match
----------------------------------------------------
state                         36          36       ✓
district                     605         605       ✓
city                        1139        1139       ✓
category                       4           4       ✓
blood_bank                  2817        2817       ✓
donor                      50000       50000       ✓
donation_event             58645       58645       ✓
blood_inventory            11159       11159       ✓

In [18]:
# ── Sample query — top 10 cities by number of blood banks ──────────────────
top_cities = pd.read_sql(
    """
    SELECT   c."City", s."State", COUNT(*) AS num_banks
    FROM     blood_bank  bb
    JOIN     city        c  ON bb.city_id     = c.city_id
    JOIN     district    d  ON c.district_id  = d.district_id
    JOIN     state       s  ON d.state_id     = s.state_id
    GROUP BY c."City", s."State"
    ORDER BY num_banks DESC
    LIMIT    10
    """,
    engine
)

print('Top 10 cities by number of blood banks:')
display(top_cities)

Top 10 cities by number of blood banks:

        City           State  num_banks
0     Mumbai     Maharashtra         66
1  Bengaluru       Karnataka         55
2    Chennai      Tamil Nadu         47
3  New Delhi           Delhi         44
4    Kolkata     West Bengal         39
5       Pune     Maharashtra         31
6  Hyderabad       Telangana         30
7     Indore  Madhya Pradesh         28
8      Thane     Maharashtra         28
9    Lucknow   Uttar Pradesh         27

In [19]:
# ── Summary statistics ──────────────────────────────────────────────────────
print('=' * 60)
print('   BLOOD BANK — TABLE GENERATION SUMMARY')
print('=' * 60)
print(f'  States / UTs        : {len(state_df):>6}')
print(f'  Districts           : {len(district_df):>6}')
print(f'  Cities              : {len(city_df):>6}')
print(f'  Categories          : {len(category_df):>6}')
print(f'  Blood Banks         : {len(blood_bank_df):>6}')
print(f'  Donors (synthetic)  : {len(donor_df):>6}')
print(f'  Donation Events     : {len(donation_event_df):>6}')
print(f'  Inventory Records   : {len(inventory_df):>6}')
print('=' * 60)
print()
print('Apheresis breakdown:')
print(blood_bank_df['Apheresis'].value_counts(dropna=False).to_string())
print()
print('Blood component availability (top 10):')
print(blood_bank_df['Blood Component Available'].value_counts().head(10).to_string())

============================================================
   BLOOD BANK — TABLE GENERATION SUMMARY
============================================================
  States / UTs        :     36
  Districts           :    605
  Cities              :   1139
  Categories          :      4
  Blood Banks         :   2817
  Donors (synthetic)  :  50000
  Donation Events     :  58645
  Inventory Records   :  11159
============================================================

Apheresis breakdown:
Apheresis
NO         1612
NaN         762
YES         414
UNKNOWN      29

Blood component availability (top 10):
Blood Component Available
NO     1253
YES    1151

---
## 9. Export All Tables to Excel

Saves every DataFrame as a separate `.xlsx` file into an `exports/` folder.  
Commit that folder to GitHub to version-control the generated tables.

In [22]:
import os

EXPORT_DIR = 'tables'
os.makedirs(EXPORT_DIR, exist_ok=True)

EXPORT_PLAN = [
    ('state',           state_df),
    ('district',        district_df),
    ('city',            city_df),
    ('category',        category_df),
    ('blood_bank',      blood_bank_df),
    ('donor',           donor_df),
    ('donation_event',  donation_event_df),
    ('blood_inventory', inventory_df),
]

print(f"Saving {len(EXPORT_PLAN)} tables to ./{EXPORT_DIR}/\n")

for table_name, df in EXPORT_PLAN:
    path = os.path.join(EXPORT_DIR, f"{table_name}.xlsx")
    df.to_excel(path, index=False, engine='openpyxl')
    size_kb = os.path.getsize(path) / 1024
    print(f"  \u2713  {table_name:<20}  {len(df):>6} rows  \u2192  {path}  ({size_kb:.1f} KB)")

print("\nDone. All files saved.")

Saving 8 tables to ./tables/

  ✓  state                     36 rows  →  tables\state.xlsx  (5.4 KB)
  ✓  district                 605 rows  →  tables\district.xlsx  (17.3 KB)
  ✓  city                    1139 rows  →  tables\city.xlsx  (29.6 KB)
  ✓  category                   4 rows  →  tables\category.xlsx  (4.8 KB)
  ✓  blood_bank              2817 rows  →  tables\blood_bank.xlsx  (562.3 KB)
  ✓  donor                  50000 rows  →  tables\donor.xlsx  (1373.6 KB)
  ✓  donation_event         58645 rows  →  tables\donation_event.xlsx  (2140.8 KB)
  ✓  blood_inventory        11159 rows  →  tables\blood_inventory.xlsx  (220.2 KB)

Done. All files saved.